### ISSUE TITLE
From 3.1.0(or some version), download link doesn't work as usual. 

### ISSUE THREAD

**Issue by RuofengX** [cadwallion/mc-velocity-docker#2] opened 2022-01-01 06:13 UTC
So, the question is: Default download link on this [page](https://velocitypowered.com/downloads) is changed to api of papermc, say `https://papermc.io/api/v2/projects/velocity/versions/3.1.1/builds/98/downloads/velocity-3.1.1-98.jar`, api add some build number in the uri. I have asked discord and it turned out that there is not any **latest** entrypoint in api/v2.  

A good news is that `https://papermc.io/api/v2/projects/velocity` will return a list of newest versions. But I am not good at using cmd to proceed json strings, any help is welcome!

btw, I write a simple docker-compose file in my fork. https://github.com/RuofengX/aisle-velocity

**Comment by cadwallion** [comment] 2022-01-01 08:26
Thank you for the report!  This seemed to work when I updated this to 3.1.0, so this must have been very recent.  I'll take a look at updating this.

**Comment by cadwallion** [comment] 2022-01-01 21:10
Alright, I can confirm on a pristine environment that this started happening on 3.1.1.  Since there's no good JSON parsing tool baked into the openjdk tool without writing java, I'm going to split this into a separate build stage that can handle the API calls and fetching of the JAR, then copy it into the final image stage.  Fix to come soon.

**Comment by cadwallion** [comment] 2022-01-04 02:09
With #2 merged, this is resolved.  Let me know if you have any further issues with this!

**Closed as completed by cadwallion** 2022-01-04 02:09 UTC

**Comment by RuofengX** [comment] 2022-01-04 08:36
Wow, using multi stage build is so cool! It fix my problem, thanks!
